<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Fody" Version="6.9.3" PrivateAssets="all" />
      <PackageReference Include="MethodBoundaryAspect.Fody" Version="2.0.150" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Harness.Abstractions\Harness.Abstractions.csproj" />
      <ProjectReference Include="..\Harness.Shared\Harness.Shared.csproj" />
    </ItemGroup>

</Project>
